# Generated by Django 2.2.10 on 2021-07-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Id', models.IntegerField()),
                ('Transaction_id', models.IntegerField()),
                ('PJPoutlet', models.IntegerField(blank=True)),
                ('Order_Date', models.DateField()),
                ('Order_Time', models.TimeField()),
                ('Order_State', models.TextField(max_length=100)),
                ('Sku_Wise_Fulfilled_Status', models.TextField(max_length=100)),
                ('Outlet_Id', models.IntegerField()),
                ('Asset', models.TextField(blank=True)),
                ('Outlet_Name', models.TextField(max_length=100)),
                ('Type', models.TextField(max_length=100)),
                ('Outlet_category', models.TextField(max_length=100)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Location', models.TextField(blank=True)),
                ('Phone_No', models.CharField(max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Owner_Name', models.TextField(max_length=100)),
                ('Mobile_No', models.CharField(max_length=12)),
                ('City', models.CharField(max_length=12)),
                ('State', models.CharField(max_length=12)),
                ('PIN', models.IntegerField(blank=True)),
                ('Area', models.CharField(max_length=12)),
                ('Warehouse', models.TextField(max_length=100)),
                ('User', models.TextField(max_length=100)),
                ('ASM', models.TextField(max_length=100)),
                ('Headquarter', models.CharField(max_length=20)),
                ('Employee_Id', models.IntegerField(blank=True)),
                ('skuid', models.IntegerField(blank=True)),
                ('SKU_Placed', models.TextField(max_length=100)),
                ('SKU_Code', models.CharField(max_length=12)),
                ('HSN_Code', models.IntegerField(default=0)),
                ('Brand', models.CharField(max_length=12)),
                ('Category', models.CharField(max_length=12)),
                ('Quantity_In_Units', models.IntegerField()),
                ('Fulfilled_Sku_Quantity', models.IntegerField(default=0)),
                ('Discount_Scheme', models.IntegerField(default=0)),
                ('Unit_Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Gross_Value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Beat', models.TextField(max_length=100)),
                ('New_District_New_Taluka', models.TextField(max_length=100)),
                ('Comment', models.TextField(blank=True)),
                ('Workflow_Reason', models.TextField(blank=True)),
                ('Through_Sale', models.TextField(blank=True)),
                ('Outlet_Potential', models.TextField(blank=True)),
                ('Focussed_Subcategory', models.TextField(blank=True)),
                ('Competitor_Products', models.TextField(blank=True)),
                ('flag', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'unique_together': {('Order_Id', 'skuid')},
            },
        ),
    ]
